### ISSUE TITLE
load fail

### ISSUE THREAD

**Issue by davephillips** [clone45/voxglitch#1]
Fedora 23 Linux
VCV Rack v1.dev

After the latest pull:

`[0.235 warn src/plugin.cpp:158] Could not load plugin ./plugins/voxglitch: Manifest contains module wavbank but it is not defined in the plugin`

Thought you'd want to know. :) Great plugin, btw.

**Comment by clone45** [comment]
I'll fix this tonight!  Thanks for the heads up!

**Comment by clone45** [comment]
Could you give it another shot?  I didn't see anything wrong with the code.  I tried renaming the .cpp file from wave_bank.cpp to wavebank.cpp in hopes that if fixes the issue.  If not, I'll dig in deeper.

**Comment by davephillips** [comment]
All good now. Both modules show in the browser, I'll check them this evening. Thanks for looking into the issue ! :)
