### ISSUE TITLE
v2: References to custom fonts are stored across frames

### ISSUE THREAD

**Issue by cschol** [clone45/voxglitch#100]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
Readout()
{
    font = APP->window->loadFont(asset::plugin(pluginInstance, "res/ShareTechMono-Regular.ttf"));
}
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by clone45** [comment]
Thank you for pointing this out.  I'll correct this soon and resubmit the modules.
