### ISSUE TITLE
Provide a way to support you (donate)

### ISSUE THREAD

**Issue by firolightfog** [clone45/voxglitch#117]
Seeing the [general appreciation](https://community.vcvrack.com/t/voxglitch-announcements-thread/14290/186) of the community I'd suggest you to add a 'Donate' option in the context menu of your modules. Or alternatively issue a non-free (expander or blank) module. 

Not expecting you receiving a fortune but it'd be nice to have a way to show our support this way.

Regards, Andras

**Comment by clone45** [comment]
That's very kind of you!  I'm working with an artist to make cool front panels for my modules.  Those will require a donation or something!  (Although, I'm paying the artist, so who knows if I'll break even! Ha ha ha.)

**Comment by clone45** [comment]
This has been completed!  I now have a patreon account.  :-)  https://www.patreon.com/voxglitch
