### ISSUE TITLE
bad link for pictures on the groovebox page

### ISSUE THREAD

**Issue by nay-seven** [clone45/voxglitch#130]
Not a big deal , but just to inform you... ;-)

btw, I have compil it for Mac/mojave here, first test are great, works fine, love it !
Again a great module, thanks !

**Comment by clone45** [comment]
Oh bummer.  I just submitted it to the VCV Rack library, so I'll have to fix the image links after it has been integrated.  Thanks so much for pointing it out, and I'm really happy that you're enjoying it!

**Comment by clone45** [comment]
This should be fixed now.  Thanks again!
