### ISSUE TITLE
Groovebox mutes

### ISSUE THREAD

**Issue by ShofB** [clone45/voxglitch#135]
It would be nice to have a way to easily mute individual samples from going to the main output.  You normally don't want the sound to go to the main stereo outs if you are using the channels direct output.

**Comment by clone45** [comment]
Thanks for the feedback.  This seems like a popular request.  In the short term, I could add this using the context menu, then try and find out a graceful way of rearranging the front panel to add the additional controls.  Would that help?

**Comment by ShofB** [comment]
Yes, but it seems that you could easily fit mute buttons under the individual outs.  It would also be very nice to have control inputs for this function.  In fact I don’t think you would need buttons on the GB if you had cv inputs.  BTW, this is a very cool device.  It is really cool having this much control over each event.  I don’t think you would need to redesign the front p[panel just add some cv inputs

ShofB
Check out my Soundcloud stream @
https://soundcloud.com/shofb

And my YouTube MyKits demos @
http://www.youtube.com/channel/UCjKNiE1s2YlJYPsAKbe8vhg

**Comment by clone45** [comment]
Thanks for the feedback!  I'm planning on adding a single POLY CV input which will provide 16 rout-able CV inputs.  I'll make sure that these can be routed to either mute or solo tracks.  I'm also experimenting with right-clicking on a track box to mute and unmute that track.  It's very intuitive so far, but I'll have to see what people think.  I'm not 100% certain about it.  Thanks again for the feedback and I'm happy that you're enjoying the module!  If you have any more requests, please send them my way.  :)

**Comment by nay-seven** [comment]
yes, always cool to have control by cv or MIDI, so cv input is ok, but a visual switch could also be useful to create MIDI learn for use with Grid MIDI controllers ? ( Lauchpads and others ) 
just a thought ;-)

**Comment by clone45** [comment]
> but a visual switch could also be useful to create MIDI learn for use with Grid MIDI controllers
@nay-seven : I love this idea, but I haven't been able to figure out how to squeeze the controls on to the front panel yet.  I agree that this is the ideal solution.  I'll keep working on this puzzle.

**Comment by ShofB** [comment]
Any thoughts on the mute going to stereo outs but not affecting the individual out.  The individual outs could easily be muted at the mixer level.

**Comment by clone45** [comment]
I'm going to close this original ticket.  I'll still try to create an option in the context menu for mutes going to stereo outs.
