### ISSUE TITLE
ByteBeat: Where did sample rate knob go?

### ISSUE THREAD

**Issue by tunefulsensation** [clone45/voxglitch#178]
Just a simple question: where did the sample rate (or pitch) knob go in bytebeat module?
I've been using it in many patches and the update broke many of them.
How can I still change its pitch? If I can't, are you planning to bring it back?
(Sorry if if is stated clearly in somewhere; I'm just terrible at reading stuff sadly.)

**Comment by clone45** [comment]
Hi @tunefulsensation!  I'm so sorry that it didn't make it into this build.  I honestly had no idea if anyone was using it.  That "pitch" knob was acting more like a clock divider, and I had plans to update it to be more flexible, but then I got too busy and skipped it.  If you need it, I'll bring it back for sure.  Are you on Windows?  If so, I can build you a custom distributable with the pitch input restored while you wait for its return.  Again, my sincere apologies.

**Comment by tunefulsensation** [comment]
I appreciate your apology, @clone45! No rush, everybody's got to do something, so I think it's great you create things in your free time! And yes, I'm on Windows, and if you feel rushed about me, please give me the custom version first so you don't need to rush the next full update. I don't want to hurry you. Please take your time! (I really want to help you, only if I could code well...)

**Comment by clone45** [comment]
Thanks so much!  Luckily, I'm between jobs and have some time to put into the project.  I had a bunch of bugs come in recently and I'm trying to get everyone up and running as quickly as possible.  Ha ha ha.  I really appreciate your support.  

Here's a distributable that should restore the pitch controls for you!  https://drive.google.com/file/d/1a-dMVYWer1e-TD8UNp2_FxMr7SnDa2b-/view?usp=sharing.  I may have placed the CV input waaaayyyy down, away from the knob.  Ha ha ha.  I'll get it properly added by the next release.

**Comment by tunefulsensation** [comment]
Sorry for the late reply. Good luck on your development! I'm actively trying to install the distributable for the first time in my life. Actually I was thinking about creating some modules myself so this may be a good starting point I guess. Thank you very much!

**Comment by clone45** [comment]
My pleasure!  I've updated the front panel design and it should be live in the next major update.  :-)  If you need any help installing the distributable, let me know!
