### ISSUE TITLE
autobreak will not compiled on MSYS2 Windows

### ISSUE THREAD

**Issue by caecos** [clone45/voxglitch#181]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nehalem -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/AutobreakStudio.cpp.o src/AutobreakStudio.cpp
In file included from src/AutobreakStudio.cpp:21:
src/AutobreakStudio/AutobreakStudio.hpp:48:44: error: field 'blink_memory_during_copy_mode' has incomplete type 'std::array<bool, 16>'
   48 |   std::array<bool, NUMBER_OF_MEMORY_SLOTS> blink_memory_during_copy_mode;
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/mingw64/include/c++/12.2.0/bits/stl_map.h:63,
                 from C:/msys64/mingw64/include/c++/12.2.0/map:61,
                 from C:/msys64/Rack-SDK/include/network.hpp:2,
                 from C:/msys64/Rack-SDK/include/rack.hpp:28,
                 from src/plugin.hpp:2,
                 from src/AutobreakStudio.cpp:7:
C:/msys64/mingw64/include/c++/12.2.0/tuple:1595:45: note: declaration of 'struct std::array<bool, 16>'
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
make: *

**Comment by clone45** [comment]
Thanks for logging this issue.  I abandon the "blinking memory" code for now, so this shouldn't be an issue.  The code on the autobreak_studio branch on github contains these fixes.  :-)

**Comment by caecos** [comment]
Compiled fine…thank’s…

Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Bret ***@***.***>
Envoyé le :lundi 19 septembre 2022 16:01
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [clone45/voxglitch] autobreak will not compiled on MSYS2 Windows (Issue #181)


Closed #181<https://github.com/clone45/voxglitch/issues/181> as completed.
