### ISSUE TITLE
fx( grain fx & satanonaut) have bypass broken

### ISSUE THREAD

**Issue by nay-seven** [clone45/voxglitch#192]
Mac os Mojave here
for both modules, bypass cut all the signal

**Comment by clone45** [comment]
Thank you for the report.  I'll see if I can implement bypass for the next release.

**Comment by clone45** [comment]
I've completed the coding for this and it will roll out in 2.21.1  🥇

**Comment by nay-seven** [comment]
Good news ! congrats ;-)

**Comment by clone45** [comment]
This has been fixed. :-)
