### ISSUE TITLE
link to autobreak studio doc in Readme.md points to autobreak doc

### ISSUE THREAD

**Issue by nodens** [clone45/voxglitch#193]
Hi,

Everything is in the title, the link in the readme points to the wrong file (sorry, on my phone and too lazy to clone + send a trivial PR ;) ).

Cheers,

**Comment by clone45** [comment]
Thanks for the heads up!  I've fixed this and should be rollling out a new version within a few days.  It should be fixed in version 2.23.1

**Comment by clone45** [comment]
This has been fixed!
