### ISSUE TITLE
Groovebox START and END are a bit glitchy

### ISSUE THREAD

**Issue by jimallman** [clone45/voxglitch#196]
Testing this in the `groovebox_design` branch.

- Sometimes an existing non-zero START value is not restored? Or perhaps it's changing as the sequence plays (click and hold the START knob to see this).

- Changes to END value can nudge START (and vice versa). This appears to be a temporary display bug, since the intended value re-appears when actually trying to edit the nudged value.

- Moving START past the END actually works and shows a different highlight color. (Is this the intended behavior? Does this mean the sound plays backward? Should this nudge the REVERSE setting?)

**Comment by clone45** [comment]
Hi Jim!  I'm not seeing the same bugs that you are.  I created a video showing the experience that I'm seeing:  https://youtu.be/LuzZE6Xb6tY

Maybe I'm misunderstanding.  Could you let me know how to recreate those bugs?

**Comment by jimallman** [comment]
Your video shows sensible behavior, and it's possible there's a different glitch on my end. (Please try merging https://github.com/clone45/voxglitch/pull/197 to try the new color schemes and let me know what you see.)

For some reason, my latest local builds are acting _weird_. Soft push-buttons aren't showing radio-button behavior, but just lighting up one after another. And choosing START, END, RATCHET doesn't show their alternate LCD displays. Odd.

I'll take a closer look using lldb to see if there are bugs that aren't showing up in Rack's log file. Hmmmmm.

**Comment by clone45** [comment]
I had to make adjustments to your code to rearrange the mapping of parameters to the correct buttons.  That threw me off for a while!  

![image](https://user-images.githubusercontent.com/1373491/201173749-d02ac616-e8e4-4a41-872f-d9aefd7e620b.png)

**Comment by jimallman** [comment]
> For some reason, my latest local builds are acting weird. 

Found it! The latest odd/missing behavior happens if we haven't chosen an outlet device for the patch. Now the alternate LCD displays are showing up for START/END/RACTHET, so I'll check again for the glitches reported above.

**Comment by jimallman** [comment]
> I had to make adjustments to your code to rearrange the mapping of parameters to the correct buttons.

Apologies, I thought we had already discussed the mismatched buttons. (I figured this was introduced when tried refactoring the button-placement code to use initial and offset positions.)

**Comment by clone45** [comment]
> Apologies, I thought we had already discussed the mismatched buttons. (I figured this was introduced when tried refactoring the button-placement code to use initial and offset positions.)

No big deal.  I'm prone to forgetting things.  :-)

**Comment by jimallman** [comment]
> Now the alternate LCD displays are showing up for START/END/RACTHET, so I'll check again for the glitches reported above.

OK, choosing an audio device seems to have fixed all [the glitches I saw above](https://github.com/clone45/voxglitch/issues/196#issuecomment-1310677780). I'm still a bit confused about what happens when START comes after END, but I'm guessing you have a plan for this.
