### ISSUE TITLE
Autobreak Studio not detecting ".WAV" files, only ".wav" (lowercase)

### ISSUE THREAD

**Issue by brylie** [clone45/voxglitch#199]
My Zoom audio recorder stores files with the ".WAV" extension in all capital letters. When loading samples into Autobreak Studio, I have to rename the file to end with ".wav" (lowercase) for the audio files to appear in the file browser. It would be more convenient if Autobreak Studio included ".WAV" files in the file browser results.

**Comment by clone45** [comment]
Hi @brylie!  That's unusual!  I wrote code to specifically accept .WAV and .wav files.  Would it be possible to send me one of your files so I can test it on my machine?  I was able to load .WAV files so far, but maybe there's something special about your files?
  
![image](https://user-images.githubusercontent.com/1373491/202233506-fb4b1257-95a6-499d-acbd-448b1a2201fd.png)

**Comment by brylie** [comment]
Sure, here is one of the wav files compressed as a zip file so I can attach it to this message.
[ZOOM0009.zip](https://github.com/clone45/voxglitch/files/10023673/ZOOM0009.zip)

**Comment by clone45** [comment]
Thanks!  I'm not having any difficultly loading it directly myself.  The audio is just a short sample, so it doesn't sound exciting, but it does seem to load OK for me.  I made a video showing the steps I took.  Are you using Windows or Mac?  I wonder if you might be using an older version of the Voxglitch modules that may have not worked properly?  Let me know!  :-)

https://youtu.be/tQ-q8vWyzB0

**Comment by brylie** [comment]
I'm using Linux with the KDE desktop. It could be that Linux/KDE uses stricter file extension filters. 

I wonder if there is another VCV Rack module that uses `osdialogue_filters_parse` for cross-platform, case-insensitive file extensions that could serve as a reference solution.

**Comment by clone45** [comment]
I'll dig in and find out!

**Comment by clone45** [comment]
Here's my posting on the forum.  Hopefully someone will have seen this before: https://community.vcvrack.com/t/osdialog-filters-parse-and-linux-kde/18743

**Comment by brylie** [comment]
Ah, good idea to post on the forum💡. Thanks 🙂

**Comment by clone45** [comment]
Hi @brylie,

Some of the forum users were able to confirm that the WAV files aren't showing up with linux/kde.  Unfortunately, this doesn't seem like something that I have the ability to fix.  However, forum members suggest that once the file selection dialog opens, to enter "wav" for search criteria, and that should cause all of the wav files to appear.  Hopefully this is a good work around for you!

Cheers,
Bret

**Comment by brylie** [comment]
Yep, thanks for pointing me in the right direction 🙂

**Comment by clone45** [comment]
My pleasure!  Sorry that I couldn't be more helpful!
