### ISSUE TITLE
One Zero module -- can file be used to set CV out?

### ISSUE THREAD

**Issue by martinkrz** [clone45/voxglitch#209]
I'm looking for a way to sequence 1000's of specific CV values.

Can One Zero be used with an external file that stores a CV value that would be output via OUT at each step?

**Comment by clone45** [comment]
No, unfortunately it can't do that.  However, I would be open minded about creating a new module for that purpose. :-) I've gone ahead and added this to my roadmap (https://voxglitch.canny.io/admin/roadmap/voxglitch-roadmap).  Thanks!

**Comment by martinkrz** [comment]
I would be more than happy to donate in support of such a module.

Many thanks,

m

Martin Krzywinski
science + art
http://mkweb.bcgsc.ca

**Comment by clone45** [comment]
That's very kind of you, Martin!  Once the module is completed, you might consider signing up to my patreon account:  https://www.patreon.com/voxglitch  :-)

**Comment by clone45** [comment]
Also, I'll try to expedite this module for you.  I'll keep you posted.

**Comment by clone45** [comment]
Hey @martinkrz , good news!  I've created the module that you've requested.  See: https://youtu.be/sNrQTug5l70.  Let me know if there's anything else you need from it!  

Here are early builds:

- Windows: https://github.com/clone45/voxglitch/suites/10134092499/artifacts/494752006
- Mac: https://github.com/clone45/voxglitch/suites/10134092499/artifacts/494752006
- Linux: https://github.com/clone45/voxglitch/suites/10134092499/artifacts/494752005

I hope that you have a happy new years!

**Comment by martinkrz** [comment]
Superb!

I would only ask for one tiny modification.

It would be great if upon the first clock tick, the module produced the
first CV value in the list, as opposed to stepping to the second CV.

The initial (pre-trigger) output could be CV = 0.

m

Martin Krzywinski
science + art
http://mkweb.bcgsc.ca

**Comment by clone45** [comment]
Easily done.  In Fact, that's how it was working, but I changed it.  Ha ha ha.  I'll have the update made in just a few minutes.

**Comment by martinkrz** [comment]
Lol, super.

Can I send you some $ via PayPal?

m

Martin Krzywinski
science + art
http://mkweb.bcgsc.ca

**Comment by clone45** [comment]
Awesome!  Done.  Here's are the new builds:

- Mac: https://github.com/clone45/voxglitch/suites/10134705768/artifacts/494789941
- Windows: https://github.com/clone45/voxglitch/suites/10134705768/artifacts/494789941
- Linux: https://github.com/clone45/voxglitch/suites/10134705768/artifacts/494789939

As for payment -- don't worry about it!  Consider this a late Christmas Gift from me.  :-)

**Comment by martinkrz** [comment]
Amazing. You *are* Santa.

BTW, the Mac link is the same as the Windows link and I need the Mac
version.

m

Martin Krzywinski
science + art
http://mkweb.bcgsc.ca

**Comment by martinkrz** [comment]
NVM, I figured out the link must have been

https://github.com/clone45/voxglitch/suites/10134705768/artifacts/494789939

Martin Krzywinski
science + art
http://mkweb.bcgsc.ca

**Comment by clone45** [comment]
I think it's this one:
https://github.com/clone45/voxglitch/suites/10134705768/artifacts/494789940

**Comment by martinkrz** [comment]
Right, that's the one.

How am I using this? Every year, I make Pi Day art.

http://mkweb.bcgsc.ca/pi

I just got into VCV Rack and wanted to created something that would read
out the digits of Pi in a generative ambient groove.

I've attached a short snippet.

Thanks again,

m

Martin Krzywinski
science + art
http://mkweb.bcgsc.ca

**Comment by clone45** [comment]
That's amazing!  I checked out your site and love your work.  Unfortunately, the attachment didn't seem to work.  If you post it to youtube or anywhere, please send me the link so I can hear it!  I love being part of these types of projects, so don't be shy if you need additional modules built.  I'd love to help!

**Comment by clone45** [comment]
Closing just to clean things up.

**Comment by martinkrz** [comment]
Thanks again!mMartin Krzywinskiscience + arthttp://mkweb.bcgsc.caOn Jan 31, 2023, at 18:40, Bret Truchan ***@***.***> wrote:﻿
Closing just to clean things up.
