### ISSUE TITLE
Grain Engine Mk2 V2.25 Loading WAV files Confusion

### ISSUE THREAD

**Issue by therealkitman** [clone45/voxglitch#214]
Hi, I was trying to load multiple wav files into into the 5 slots. Each time I selected a slot other than slot 1 the wav file would overwrite the currently loaded wav in slot 1. Found I needed to change the Sample knob to match the slot position desired. Selecting a slot itself from the context menu makes no difference.

This is kind of confusing.

Also is the Sample knob meant to blend between wav files or just a hard switch?

![image](https://user-images.githubusercontent.com/14888092/212282042-40a60cdf-4597-4b55-9c36-1ec7ae7be8ca.png)

![image](https://user-images.githubusercontent.com/14888092/212283071-6dcdb921-55e6-4a14-96c9-bb6726e1e69b.png)

**Comment by clone45** [comment]
Oh wow, that's quite a big bug!  Thanks for reporting it.  Switching between samples is a "hard switch", not blended.  That was the extent of my capabilities when I wrote the module, and perhaps someday I'll revisit it to see if I can smoothly blend between the samples.  :-)  I'll get that bug fixed as soon as possible, however there's already a bugfix in the vcv rack library queue to be built, so I'll have to wait until it's completed before patching this new bug.  Again, thanks!!

**Comment by therealkitman** [comment]
Could I add something? The Jitter control doesn't seem to do anything on the Mk2. But on Ghosts jitter gets me a sound like I had on Borderlands many years ago. Loving Ghosts!!!

**Comment by clone45** [comment]
I'll take a look!  Also, quick update -- I just fixed the bug that you reported and it'll ship out with the next update.

**Comment by therealkitman** [comment]
Oh thankee!!!!!! These 2 synths are easier to control than Clouds or Supercell - plus I get the sounds I want.

**Comment by clone45** [comment]
Jitter seems to work for me!  I made a little video to show you what I'm seeing: https://youtu.be/QLtBnWe0kZ4

Let me know if you're getting some other behavior!

**Comment by clone45** [comment]
PS: I love them too!  I get completely lost in the sound that they make.  :-)

**Comment by therealkitman** [comment]
I just watched the video. I get that harsh buzz on the full counter clockwise poistion but no changes in noise with any movement clockwise. Mine is a linux system. I'll try another wave file this afternoon. Thanks.

**Comment by clone45** [comment]
I'd be interested to see what you find out.  The "harsh buzz" is created when a bunch of the grains start to overlap, which causes amplification of the sound.  When you have a chance, could you let me know what sample rate you're using in rack?  Maybe I made a mistake by not supporting all sample rates.  I'm running at 44.1 kHz or 48 kHz

![image](https://user-images.githubusercontent.com/1373491/212445795-2b174193-beb0-44d9-9ea9-fe750bd1efac.png)

**Comment by therealkitman** [comment]
I watch the video again. Any variance in audio in that video from the jitter knob is so subtle that I think my brain is making it up :) I'm not sure I'm hearing anything compared to the great in-your-face jitter on Ghosts.

I tried 3 wav files and at both 44.1 and 48kHz and I can't perceive any variance with jitter. Odd.

My sound card is just what is onboard the motherboard so not top range gear and 25 year old  gaming speakers.

**Comment by clone45** [comment]
Closing this ticket.  Please let me know if you need anything else!

**Comment by therealkitman** [comment]
V2.26.1 tests ok :+1: 
Thanks.
