### ISSUE TITLE
Failed to load SVG

### ISSUE THREAD

**Issue by cschol** [clone45/voxglitch#232]
```
[9.277 warn src/window/Svg.cpp:112 load] Failed to load SVG /home/src/Rack-2.0-Home/plugins-lin-x64/voxglitch/res/components/DigitalSwitchOff.svg
```
This file does not seem to exist in the repository.

**Comment by clone45** [comment]
Ok, I'll get this fixed and let you know when it's done.  Sorry about that.

**Comment by clone45** [comment]
Fixed.  ec4851ed1fb75ac82a18dab8929c1ede3c0d40d0 

My updates include:

1. Restored two missing svg files
2. Removed two DEBUG statements
3. Searched the rack log file for any other issues and found none

Thanks!

**Comment by cschol** [comment]
The error message is gone, but something is still off here:

![image](https://github.com/clone45/voxglitch/assets/624427/2ff418cb-c83e-4160-acd1-74ed3bcd545d)

This is the ArpSeq.

**Comment by clone45** [comment]
Thanks.  I'm looking into this right now.

**Comment by clone45** [comment]
Sorry for the trouble.  I was able to recreate the issue.  The error was related to a capitalization error in the theme folder name.  I fixed the issue and also added code to prevent this from happening in the future.

683d2fd859361f96af6bd1d3f76102eee178f9b8
