### ISSUE TITLE
Feature Request: Voxglitch on 4ms MetaModule?

### ISSUE THREAD

**Issue by offthesky** [clone45/voxglitch#240]
I use and LOVE voxglitch modules all the time!!  I'm no coder and thus am wondering if they might be able to ever be ported somehow over into the upcoming Eurorack - 4ms MetaModule format? 

https://github.com/4ms/metamodule-plugin-sdk

Many thanks in advance, for the joy voxglitch modules have brought to my creative workflow!

**Comment by clone45** [comment]
> Many thanks in advance, for the joy voxglitch modules have brought to my creative workflow!

My pleasure!  

> I'm no coder and thus am wondering if they might be able to ever be ported somehow over into the upcoming Eurorack - 4ms MetaModule format?

I'm all for it, but unfortunately I don't have the time right now to do it.  And when I theoretically get time, there's a slew of updates that I need to make to the rack modules that will need to take priority.  Are there any specific modules that you would like to see ported to it?  I'm open minded about having other developers help out, if there's anyone who would want to try it out.  :-)

**Comment by offthesky** [comment]
well that's really great to hear its possible at least! my fingers are crossed they could be ported in good time...

and as far as the ones i think would be super useful for the community?  XY, digital sequencer, grain fx, ghosts, and satanonaut - well i might be a bit biased as those are my all time favorites ;)

**Comment by clone45** [comment]
Ghosts and Satanonaut might be a very possible!  They're relatively straightforward when it comes to the user interfaces, which would be the difficult parts to port over.  Digital Sequencer would be a real challenge.  It's got a lot of custom drawn components and interaction.  I'll keep this in the back of my head.  

In the past, I've considered upgrading my modules, such as Digital Sequencer, with more features.  However, more recently, I've been leaning toward keeping things simple and trying to make the modules as portable as possible.  Maybe the next generation of AI will be able to make the changes for me.  :-)

**Comment by offthesky** [comment]
having ghosts and satanaut would certainly be really awesome! as i don't think there will be many granular/glitchy effects options to begin with.. 

with metamodule- i have a feeling many modules from different devs - things that require a lot of mouse input (like XY, digital sequencer) would have to just have very limited functionality directly on the MM- mainly need to be fully setup on the laptop.. 4ms have stated several times "it will work best/be funnest to build the patches on the computer, then use the 8 hardware knobs to control a few things".  or i guess in the case of your XY module, inputs could added that would allow one to patch up knobs to it and record x and y using the physical knobs? that could also be fun to have in VCV as well (recording via midi faders or whatever)... oops sorry to feature creep there ;) anyway, all fun stuff to think about!

well if when you ever have time to get around to porting any of these- if you want any help in the graphics dept, i was a graphic/ux designer for 20 years before going into audio full time so i'm happy to lend a hand there to ease the load if need be!

**Comment by clone45** [comment]
> if you want any help in the graphics dept, i was a graphic/ux designer for 20 years before going into audio full time so i'm happy to lend a hand there to ease the load if need be!

Thanks!  Maybe someday we can collaborate on a module.  :-)

**Comment by clone45** [comment]
The metamodule has limitations in the types of development I can do with it.  It doesn't support file loading, or custom mouse interactions.  That rules out a majority of my modules, so at least for the short term, I'm afraid that I'm not going to be putting development effort into it.  My sincere apologies.  It's a cool module!

**Comment by clone45** [comment]
Closed - won't do - for now.
