### ISSUE TITLE
Incorrectly formed SVGs?

### ISSUE THREAD

**Issue by falkTX** [clone45/voxglitch#243]
When packaging for Cardinal I noticed one of the tests failing, due to SVG not being able to be parsed.

Simple reproducible steps using python:

```
python3 -c "import xml.etree.ElementTree as ET; ET.parse('res/ghosts/ghosts_panel.svg')"
```

This fails with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: unbound prefix: line 2, column 0
```

Are you doing anything special with this svg? Other ones seem fine, but this one seems to be invalid..?

**Comment by falkTX** [comment]
Found the issue, there was a missing prefix for `xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"` so validation failed. I guess you hand edited this one at some point.

Added as fix in e609066b6371d2b8e3058a374bdaa50c17762407 which is part of #242

**Comment by clone45** [comment]
@falkTX Yes, I had experimented with a script that stripped out and combined tagging.  I guess I was a bit too overzealous.  Sorry for the inconvenience.

**Comment by falkTX** [comment]
such stuff happens, I was not expecting svg validation to fail in python, as the svg works everywhere else. oh well. thanks for merging
