### ISSUE TITLE
Digital Seq snapping issue

### ISSUE THREAD

**Issue by pizzathehut893** [clone45/voxglitch#245]
Hello!
I use your sequencer modules frequently and love them.  I've noticed that the snap feature in both of the digital sequencers appear to not do anything for me now.  I can't tell if it's my issue from doing something wrong, or something had changed.  

It's not a big problem by any means.  Thank you for taking the time to develop everything you have!

**Comment by clone45** [comment]
Ah, that's unfortunate!  I had made some fundamental updates to the sequencers, and I must have inadvertently broken the snapping feature.  In addition, another user noted that the randomize feature only affects the first 16 steps.  I'll try to fix this soon.  Thanks for the bug report!

**Comment by clone45** [comment]
FYI: This is fixed and should be rolling out soon!

**Comment by clone45** [comment]
Done!

**Comment by pizzathehut893** [comment]
Thank you very much!!
