### ISSUE TITLE
Digital Sequencer crashing

### ISSUE THREAD

**Issue by dantveita** [clone45/voxglitch#34]
DS is crashing Rack when clicking on it in the module browser

[4.885 fatal src/main.cpp:45] Fatal signal 11. Stack trace:
15: 1   Rack                                0x00000001018a33cd _ZL18fatalSignalHandleri + 45
14: 2   libsystem_platform.dylib            0x00007fff6c8fe42d _sigtramp + 29
13: 3   ???                                 0x0000000000000001 0x0 + 1
12: 4   Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
11: 5   Rack                                0x00000001018cdfec _ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE + 92
10: 6   Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
9: 7   Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
8: 8   Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
7: 9   Rack                                0x0000000101907769 _ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE + 121
6: 10  Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
5: 11  Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
4: 12  Rack                                0x0000000101903214 _ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE + 52
3: 13  Rack                                0x000000010190746e _ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE + 334
2: 14  Rack                                0x00000001018bb2f3 _ZN4rack6Window3runEv + 1395
1: 15  Rack                                0x00000001018a2efa main + 1434
0: 16  Rack                                0x000000010183c034 start + 52

**Comment by clone45** [comment]
Thank you for the bug report.  I'll look into this ASAP.  Are you on Mac, PC, or Linux?

**Comment by clone45** [comment]
@dantveita Should be fixed in 1.7.1.  Submitting to the user library right now.  Hopefully the fixed version will be distributed soon!
