### ISSUE TITLE
latest pull fails to build, with solution

### ISSUE THREAD

**Issue by davephillips** [clone45/voxglitch#56]
Greetings ! I'm on Ububtu 18.05 with GCC 7.5.0. The latest commit will failed with this error:

```
g++  -std=c++11 -Wsuggest-override   -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=athlon-fx -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -c -o build/src/GrainEngineMK2Expander.cpp.o src/GrainEngineMK2Expander.cpp
In file included from src/GrainEngineMK2Expander.cpp:13:0:
src/GrainEngineMK2Expander/GrainEngineMK2Expander.hpp:1:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
```

The solution for pre-8.x GCC is:

`#include <experimental/filesystem>`

That works for me. You might want to add an #ifdef regarding the GCC version.

Best,

dp

**Comment by clone45** [comment]
Ah, thanks Dave!  The <filesystem> include turned out not to be necessary, but I forgot to remove it.  I'll get that fixed asap.  I appreciate the heads up!

**Comment by clone45** [comment]
Updated!  :-)

**Comment by davephillips** [comment]
Thanks ! Gotta have my Voxglitch !! :)
