### ISSUE TITLE
Digital Sequencer - Reset or Gate not working at all 

### ISSUE THREAD

**Issue by MaxPleaner** [clone45/voxglitch#73]
Hi, I'm not sure if this was a feature regression, but as you can see in the attached video, neither Reset input or Gate output are working at all. I tried both Reset modes. It's v1.25.0 and I'm running VCV 1.1.6 on Windows.

https://user-images.githubusercontent.com/5035719/113189618-41712c00-9210-11eb-8194-d5667d08e38a.mp4

**Comment by clone45** [comment]
Hi Max!  The reset input expects a value from 0 to 10 "volts".  If you use the Button module from RJModules, it works just fine.  But the Alikins Momentary On Buttons module only ranges from 0 to 5.  According to the VCV Rack standards, and gate signal should produce an output of 10 when "On" (see https://vcvrack.com/manual/VoltageStandards).  

What I could do is add an option to trigger on 5 volts?  Let me know what you think!

**Comment by MaxPleaner** [comment]
Ok sure, I can just use a different button module. What about the gate
though? I still am not saying anything produced by that output

**Comment by clone45** [comment]
Sorry for overlooking that part of your question.  The gate sequencer is underneath the CV sequencer, as shown here:

![gates](https://user-images.githubusercontent.com/1373491/113242442-d81c0800-9265-11eb-9e80-a0258de18424.jpg)

I hope that helps!

**Comment by MaxPleaner** [comment]
Ok awesome. All sorted out then. Thanks so much for fast responses.

**Comment by clone45** [comment]
You bet!  Any time!

**Comment by MaxPleaner** [comment]
I already closed this issue, but I do think it would be helpful to support 5 volt ... a lot of modules give triggers at 5 volt. For example the Drum Sequencer I showed in my video (SV Modular ) also gives 5 volt output from the triggers (which I am using to reset Voxglitch Digital Sequencer)... it's not a problem now that I understand what's going on, I can just double the voltage there, but it's an extra step that I haven't found necessary in many other modules

**Comment by clone45** [comment]
I agree that it would be a good idea.  I'll try to code that up over the weekend. :-)
