### ISSUE TITLE
Digital Sequencer: Dragging Action Crashes VCV Rack

### ISSUE THREAD

**Issue by jonheal** [clone45/voxglitch#83]
https://user-images.githubusercontent.com/33180867/121777925-7aa80f80-cb62-11eb-8f18-af860579551b.mp4

I found a repeatable action that crashes Rack. If I click on an active Gate cell and then drag the mouse to the left without releasing the mouse button, Rack crashes when the cursor reaches the left edge of Digital Sequencer.

**Comment by clone45** [comment]
Hi Jon!  Whoops!  Sorry about that bug.  I've patched it and submitted the bug patch to VCV Rack.  (1.30.1: https://github.com/VCVRack/library/issues/626)

Thank you so much for reporting it,
Bret
