### ISSUE TITLE
WAV bank pitch shifting gets grainy on long samples

### ISSUE THREAD

**Issue by 44100hertz** [clone45/voxglitch#93]
On long samples (over 1 minute 30 seconsd on my machine) the WAV bank pitch control gets more and more grainy the longer the sample is played. I looked at the code and I'm not sure why this happens, but my theory is that its due to storing sample position as a float rather than a double.

**Comment by bret-2600** [comment]
This is really interesting.  I'll take a peek at it this weekend.  Thanks for reporting it!  I wonder if my granulators have the same issue.

**Comment by clone45** [comment]
This is really interesting. I'll take a peek at it this weekend. Thanks for reporting it! I wonder if my granulators have the same issue.

**Comment by clone45** [comment]
Hi @44100hertz , when you say "grainy", do you mean that it becomes less continuous?  I just pulled in a long sample and attached a knob module to the pitch input, and it seems to jump significantly (and discretely) between pitches.  Is that what you're experiencing as well?  It definitely seems like a bug to me, most likely in my pitch calculations.  Let me know if this is what you're experiencing and I'll dive in deeper to figure out why it's happening.  

Quick follow up.  Is seems like you were 100% correct!  When I changed sample position from a float to a double, it solved the issue.  I'm going to do an audit of the other modules and submit the fix to VCV Rack as soon as I have time.  (Within the next few days for sure.)

Thanks a ton for pointing this out to me!

**Comment by clone45** [comment]
Holy crap.  I owe you _so many_ beers.  This seems to be an issue with my granular modules as well.  I'm so excited to fix this!!

**Comment by 44100hertz** [comment]
> Hi @44100hertz , when you say "grainy", do you mean that it becomes less continuous? I just pulled in a long sample and attached a knob module to the pitch input, and it seems to jump significantly (and discretely) between pitches. Is that what you're experiencing as well?

Yes this is exactly what I was referring to. I'm glad that the bug is being patched so readily.
